### ISSUE TITLE
Round robin scheduler for Linux 3.18

### ISSUE THREAD

**Issue by lihas** [samuei/EECS-678-Round-Robin-Linux-Scheduler#1]
I am Sahil. As a hobby project I have undertaken the task of creating a simple round robin scheduler for Linux 3.18. I followed the directions given in the pdf document given by you. Since last 2 weeks I have been stuck with a strange problem. When I run 2 processes of my scheduling class, the kernel crashes due to a null pointer dereference in pick_next_task_fair(). In that function although nr_running is not zero, still pick_next_entity() returns NULL, due to which when set_next_entity() is called from pick_next_task() a null pointer dereference occurs. I am hoping that while implementing a scheduler you might have faced a similar problem, and if so I am looking forward for you to share some experience.

**Comment by samuei** [comment]
I'm afraid we didn't run into any problems similar to this. Our project was for a patch on Linux 2.6.32.60, not for 3.18, though. You may want to compare the relevant processes between these two versions, since their implementations may have changed substantially.

Good luck.
